blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions & Q&A
    url: https://github.com/omnikit-tools/omnikit-issues
    about: If you need help or want to discuss ideas, please ask here.
